const express = require("express");
const router = express.Router();
const SiteController = require("../app/Controller/SiteController");
const multer = require("multer");
const upload = multer();
router.post("/likeVideos", upload.none(), SiteController.likeVideos);
router.post("/handleFollow", SiteController.handleFollow);
router.get("/following/:author", SiteController.following);
router.get("/listFollow/:author", SiteController.getListFollow);
router.get("/", SiteController.home);
module.exports = router;
